# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate Release

on:
  push:
    branches: [ release_letssteam ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        sudo apt --yes install gcc-arm-none-eabi
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Compile stm32f103xb_bl
      run: |
        python tools/progen_compile.py -t make_gcc_arm --clean --parallel stm32f103xb_bl
        
    - name: Compile stm32f103xb_stm32wb55rg_if
      run: |
        python tools/progen_compile.py -t make_gcc_arm --clean --parallel stm32f103xb_stm32wb55rg_if
        
    - name: Compile stm32f103xb_stm32l475vg_if
      run: |
        python tools/progen_compile.py -t make_gcc_arm --clean --parallel stm32f103xb_stm32l475vg_if
        
    - name: Compile stm32f103xb_steami32_if
      run: |
        python tools/progen_compile.py -t make_gcc_arm --clean --parallel stm32f103xb_steami32_if
        

    - name: Set environment variable
      run: echo "RELEASE_NAME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Generate Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.RELEASE_NAME }}
        prerelease: false
        make_latest: true
        files: |
          projectfiles/make_gcc_arm/stm32f103xb_bl/build/stm32f103xb_bl.bin
          projectfiles/make_gcc_arm/stm32f103xb_bl/build/stm32f103xb_bl_crc.bin
          projectfiles/make_gcc_arm/stm32f103xb_bl/build/stm32f103xb_bl_crc.txt
          projectfiles/make_gcc_arm/stm32f103xb_stm32wb55rg_if/build/stm32f103xb_stm32wb55rg_if.bin
          projectfiles/make_gcc_arm/stm32f103xb_stm32wb55rg_if/build/stm32f103xb_stm32wb55rg_if_crc.bin
          projectfiles/make_gcc_arm/stm32f103xb_stm32wb55rg_if/build/stm32f103xb_stm32wb55rg_if_crc.txt
          projectfiles/make_gcc_arm/stm32f103xb_stm32l475vg_if/build/stm32f103xb_stm32l475vg_if.bin
          projectfiles/make_gcc_arm/stm32f103xb_stm32l475vg_if/build/stm32f103xb_stm32l475vg_if_crc.bin
          projectfiles/make_gcc_arm/stm32f103xb_stm32l475vg_if/build/stm32f103xb_stm32l475vg_if_crc.txt
          projectfiles/make_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.bin
          projectfiles/make_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if_crc.bin
          projectfiles/make_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if_crc.txt
        